#ifndef JSON_OPTIONS_H
#define JSON_OPTIONS_H

#define JSON_LIBRARY
#define JSON_ISO_STRICT
#define JSON_SAFE
#define JSON_STDERROR
//#define JSON_UNICODE
#define JSON_REF_COUNT
#define JSON_ITERATORS
#define JSON_WRITE_PRIORITY MED
#define JSON_READ_PRIORITY HIGH
#define JSON_ESCAPE_WRITES
#define JSON_CASE_INSENSITIVE_FUNCTIONS
#define JSON_BOOL_TYPE char
#define JSON_NUMBER_TYPE float
#define JSON_CASTABLE
#define JSON_SECURITY_MAX_NEST_LEVEL 128
#define JSON_SECURITY_MAX_STRING_LENGTH 33554432
#define JSON_SECURITY_MAX_STREAM_OBJECTS 128
#define JSON_NO_EXCEPTIONS

#endif
